#!/bin/bash

# torture test mach; set up a lot of distro's and build a few packages in it

SPECS="ladspa.spec"
DISTS="rh72 rh72u rh73 rh73u rh80 rh80u rh80fs rh80ft rh80fu rh9 rh9u rh9fs rh9ft rh9fu"
error=no
for dist in $DISTS;
do
  echo "+ torturing $dist"
  #../scripts/mach -r $dist clean
  ../scripts/mach -r $dist build $SPECS || error=yes
  ../scripts/mach -r $dist clean
  if test x$error == xyes;
  then
    echo "- dist $dist failed"
    failed="$failed $dist"
    error=no
  fi
done
if test x$failed != x;
then
  echo Failed distro's:$failed
fi


